export const getConfidence = (con) => {
    switch (con) {
        case "n":
            return "Normal";
        case "h":
            return "Alta";
        case "l":
            return "Baja";
        default:
            return "";
    }
};

export const formatHour = (hour) => {
    // Hour comes in a number like: 344 (3:44), 1234 (12:34).
    // We need to convert it to a string and add a leading zero if needed.
    const hourStr = hour.toString();
    if (hourStr.length === 3) {
        return `0${hourStr[0]}:${hourStr.slice(1)}`;
    } else if (hourStr.length === 4) {
        return `${hourStr.slice(0, 2)}:${hourStr.slice(2)}`;
    }
    return "";

};

export const comunas = ['AISEN', 'ALGARROBO', 'ALHUE', 'ALTO DEL CARMEN', 'ANCUD',
        'ANDACOLLO', 'ANGOL', 'ANTOFAGASTA', 'ANTUCO', 'ARAUCO', 'ARICA',
        'BUIN', 'BULNES', 'CABILDO', 'CABRERO', 'CALAMA', 'CALBUCO',
        'CALDERA', 'CALERA', 'CALERA DE TANGO', 'CALLE LARGA', 'CAMARONES',
        'CAMINA', 'CANELA', 'CANETE', 'CARAHUE', 'CARTAGENA', 'CASABLANCA',
        'CASTRO', 'CATEMU', 'CAUQUENES', 'CERRILLOS', 'CERRO NAVIA',
        'CHAITEN', 'CHANARAL', 'CHANCO', 'CHEPICA', 'CHIGUAYANTE',
        'CHILE CHICO', 'CHILLAN', 'CHILLAN VIEJO', 'CHIMBARONGO',
        'CHONCHI', 'CISNES', 'COBQUECURA', 'COCHAMO', 'COCHRANE',
        'CODEGUA', 'COELEMU', 'COIHAIQUE', 'COIHUECO', 'COINCO', 'COLBUN',
        'COLCHANE', 'COLINA', 'COLLIPULLI', 'COLTAUCO', 'COMBARBALA',
        'CONCEPCION', 'CONCHALI', 'CONCON', 'CONSTITUCION', 'CONTULMO',
        'COPIAPO', 'COQUIMBO', 'CORONEL', 'CORRAL', 'CUNCO', 'CURACAUTIN',
        'CURACAVI', 'CURACO DE VELEZ', 'CURANILAHUE', 'CURARREHUE',
        'CUREPTO', 'CURICO', 'DALCAHUE', 'DIEGO DE ALMAGRO', 'DONIHUE',
        'EL BOSQUE', 'EL CARMEN', 'EL MONTE', 'EL QUISCO', 'EL TABO',
        'EMPEDRADO', 'ERCILLA', 'ESTACION CENTRAL', 'FLORIDA', 'FREIRE',
        'FREIRINA', 'FRESIA', 'FRUTILLAR', 'FUTALEUFU', 'FUTRONO',
        'GALVARINO', 'GENERAL LAGOS', 'GORBEA', 'GRANEROS', 'HIJUELAS',
        'HUALAIHUE', 'HUALANE', 'HUALQUI', 'HUARA', 'HUASCO', 'HUECHURABA',
        'ILLAPEL', 'INDEPENDENCIA', 'IQUIQUE', 'ISLA DE MAIPO', 'LA CRUZ',
        'LA ESTRELLA', 'LA FLORIDA', 'LA GRANJA', 'LA HIGUERA', 'LA LIGUA',
        'LA PINTANA', 'LA SERENA', 'LA UNION', 'LAGO RANCO', 'LAGO VERDE',
        'LAGUNA BLANCA', 'LAJA', 'LAMPA', 'LANCO', 'LAS CABRAS',
        'LAS CONDES', 'LAUTARO', 'LEBU', 'LICANTEN', 'LIMACHE', 'LINARES',
        'LITUECHE', 'LLAILAY', 'LLANQUIHUE', 'LO BARNECHEA', 'LO ESPEJO',
        'LOLOL', 'LONCOCHE', 'LONGAVI', 'LONQUIMAY', 'LOS ALAMOS',
        'LOS ANDES', 'LOS ANGELES', 'LOS LAGOS', 'LOS MUERMOS',
        'LOS SAUCES', 'LOS VILOS', 'LOTA', 'LUMACO', 'MACHALI', 'MACUL',
        'MAFIL', 'MAIPU', 'MALLOA', 'MARCHIHUE', 'MARIA ELENA',
        'MARIA PINTO', 'MARIQUINA', 'MAULE', 'MAULLIN', 'MEJILLONES',
        'MELIPEUCO', 'MELIPILLA', 'MOLINA', 'MONTE PATRIA', 'MOSTAZAL',
        'MULCHEN', 'NACIMIENTO', 'NANCAGUA', 'NATALES', 'NAVIDAD',
        'NEGRETE', 'NINHUE', 'NIQUEN', 'NOGALES', 'NUEVA IMPERIAL',
        'NUNOA', "O'HIGGINS", 'OLIVAR', 'OLLAGUE', 'OLMUE', 'OSORNO',
        'OVALLE', 'PADRE HURTADO', 'PADRE LAS CASAS', 'PAIGUANO',
        'PAILLACO', 'PAINE', 'PALENA', 'PALMILLA', 'PANGUIPULLI',
        'PANQUEHUE', 'PAPUDO', 'PAREDONES', 'PARRAL',
        'PEDRO AGUIRRE CERDA', 'PELARCO', 'PELLUHUE', 'PEMUCO', 'PENAFLOR',
        'PENALOLEN', 'PENCAHUE', 'PENCO', 'PERALILLO', 'PERQUENCO',
        'PETORCA', 'PEUMO', 'PICA', 'PICHIDEGUA', 'PICHILEMU', 'PINTO',
        'PIRQUE', 'PITRUFQUEN', 'PLACILLA', 'PORTEZUELO', 'PORVENIR',
        'POZO ALMONTE', 'PRIMAVERA', 'PROVIDENCIA', 'PUCHUNCAVI', 'PUCON',
        'PUDAHUEL', 'PUENTE ALTO', 'PUERTO MONTT', 'PUERTO OCTAY',
        'PUERTO VARAS', 'PUMANQUE', 'PUNITAQUI', 'PUREN', 'PURRANQUE',
        'PUTAENDO', 'PUTRE', 'PUYEHUE', 'QUEILEN', 'QUELLON', 'QUEMCHI',
        'QUILACO', 'QUILICURA', 'QUILLECO', 'QUILLON', 'QUILLOTA',
        'QUILPUE', 'QUINCHAO', 'QUINTA DE TILCOCO', 'QUINTA NORMAL',
        'QUINTERO', 'QUIRIHUE', 'RANCAGUA', 'RANQUIL', 'RAUCO', 'RECOLETA',
        'RENAICO', 'RENCA', 'RENGO', 'REQUINOA', 'RETIRO', 'RINCONADA',
        'RIO BUENO', 'RIO CLARO', 'RIO HURTADO', 'RIO IBANEZ', 'RIO NEGRO',
        'ROMERAL', 'SAAVEDRA', 'SAGRADA FAMILIA', 'SALAMANCA',
        'SAN ANTONIO', 'SAN BERNARDO', 'SAN CARLOS', 'SAN CLEMENTE',
        'SAN ESTEBAN', 'SAN FABIAN', 'SAN FELIPE', 'SAN FERNANDO',
        'SAN GREGORIO', 'SAN IGNACIO', 'SAN JAVIER', 'SAN JOAQUIN',
        'SAN JOSE DE MAIPO', 'SAN JUAN DE LA COSTA', 'SAN MIGUEL',
        'SAN NICOLAS', 'SAN PABLO', 'SAN PEDRO', 'SAN PEDRO DE ATACAMA',
        'SAN PEDRO DE LA PAZ', 'SAN RAFAEL', 'SAN RAMON', 'SAN ROSENDO',
        'SAN VICENTE', 'SANTA BARBARA', 'SANTA CRUZ', 'SANTA JUANA',
        'SANTA MARIA', 'SANTIAGO', 'SANTO DOMINGO', 'SIERRA GORDA',
        'TALAGANTE', 'TALCA', 'TALCAHUANO', 'TALTAL', 'TEMUCO', 'TENO',
        'TEODORO SCHMIDT', 'TIERRA AMARILLA', 'TILTIL', 'TIMAUKEL',
        'TIRUA', 'TOCOPILLA', 'TOLTEN', 'TOME', 'TORTEL', 'TRAIGUEN',
        'TREGUACO', 'TUCAPEL', 'VALDIVIA', 'VALLENAR', 'VALPARAISO',
        'VICHUQUEN', 'VICTORIA', 'VICUNA', 'VILCUN', 'VILLA ALEGRE',
        'VILLARRICA', 'VINA DEL MAR', 'VITACURA', 'YERBAS BUENAS',
        'YUMBEL', 'YUNGAY', 'ZAPALLAR'];
